Open "t2w_BICYCLE.xlsx" with pandas

In [1]:
import pandas as pd

df = pd.read_excel("t2w_BICYCLE.xlsx")
df.head()

,county_name,district_name,mode,mode_name,pop_total,pop_mode,percent
0,Alameda,4,BICYCLE,Bicycle,1378947,19518,1.415428
1,Butte,3,BICYCLE,Bicycle,175797,4604,2.618930
2,Contra Costa,4,BICYCLE,Bicycle,935733,5501,0.587881
3,El Dorado,3,BICYCLE,Bicycle,166652,1246,0.747666
4,Fresno,6,BICYCLE,Bicycle,702651,4021,0.572261

Sort the data by "district_name"

In [2]:
df_sorted = df.sort_values(by="district_name")
df_sorted.to_excel("t2w_BICYCLE.xlsx", index=False)
df_sorted.head()

,county_name,district_name,mode,mode_name,pop_total,pop_mode,percent
5,Humboldt,1,BICYCLE,Bicycle,116123,2845,2.449988
12,Mendocino,1,BICYCLE,Bicycle,74796,26914,35.983208
32,Siskiyou,2,BICYCLE,Bicycle,33365,277,0.830211
31,Shasta,2,BICYCLE,Bicycle,139792,640,0.457823
20,Sacramento,3,BICYCLE,Bicycle,1209828,465332,38.462658

Drop the column "county_name"

In [3]:
df_sorted = df_sorted.drop(columns=["county_name"])
df_sorted.to_excel("t2w_BICYCLE.xlsx", index=False)
df_sorted.head()

    district_name     mode mode_name  pop_total  pop_mode    percent
5               1  BICYCLE   Bicycle     116123      2845   2.449988
12              1  BICYCLE   Bicycle      74796     26914  35.983208
32              2  BICYCLE   Bicycle      33365       277   0.830211
31              2  BICYCLE   Bicycle     139792       640   0.457823
20              3  BICYCLE   Bicycle    1209828    465332  38.462658

Clear the "percent" column

In [4]:
df_sorted["percent"] = None
df_sorted.to_excel("t2w_BICYCLE.xlsx", index=False)
df_sorted.head()

    district_name     mode mode_name  pop_total  pop_mode percent
5               1  BICYCLE   Bicycle     116123      2845    None
12              1  BICYCLE   Bicycle      74796     26914    None
32              2  BICYCLE   Bicycle      33365       277    None
31              2  BICYCLE   Bicycle     139792       640    None
20              3  BICYCLE   Bicycle    1209828    465332    None

Merge the rows for each "district_name"

In [5]:
df_merged = df_sorted.groupby("district_name", as_index=False).agg({
    **{col: "first" for col in df_sorted.columns if col not in ["pop_total", "pop_mode", "district_name"]},
    "pop_total": "sum",
    "pop_mode": "sum"
})
df_merged.to_excel("t2w_BICYCLE.xlsx", index=False)
df_merged.head()

   district_name     mode mode_name percent  pop_total  pop_mode
0              1  BICYCLE   Bicycle    None     190919     29759
1              2  BICYCLE   Bicycle    None     173157       917
2              3  BICYCLE   Bicycle    None    2251682    638263
3              4  BICYCLE   Bicycle    None    6681497    212926
4              5  BICYCLE   Bicycle    None    1258819    164961

Calculate the "percent" by formula: "pop_mode"/"pop_total"*100

In [6]:
df_merged["percent"] = (df_merged["pop_mode"] / df_merged["pop_total"]) * 100
df_merged.to_excel("t2w_BICYCLE.xlsx", index=False)
df_merged.head()

   district_name     mode mode_name    percent  pop_total  pop_mode
0              1  BICYCLE   Bicycle  15.587239     190919     29759
1              2  BICYCLE   Bicycle   0.529577     173157       917
2              3  BICYCLE   Bicycle  28.346054    2251682    638263
3              4  BICYCLE   Bicycle   3.186801    6681497    212926
4              5  BICYCLE   Bicycle  13.104426    1258819    164961