Open "t2w_WALK.xlsx" with pandas

In [1]:
import pandas as pd

df = pd.read_excel("t2w_WALK.xlsx")
df.head()

,county_name,district_name,mode,mode_name,pop_total,pop_mode,percent
0,Alameda,4,WALK,Walked to work,1378947,47930,3.475841
1,Butte,3,WALK,Walked to work,175797,6564,3.733852
2,Contra Costa,4,WALK,Walked to work,935733,15985,1.708286
3,El Dorado,3,WALK,Walked to work,166652,3154,1.892567
4,Fresno,6,WALK,Walked to work,702651,14892,2.119402

Sort the data by "district_name"

In [2]:
df_sorted = df.sort_values(by="district_name")
df_sorted.to_excel("t2w_WALK.xlsx", index=False)
df_sorted.head()

,county_name,district_name,mode,mode_name,pop_total,pop_mode,percent
9,Lake,1,WALK,Walked to work,4395274,182448,4.151004
13,Mendocino,1,WALK,Walked to work,127885,5170,4.042695
5,Humboldt,1,WALK,Walked to work,116123,6284,5.411503
37,Tehama,2,WALK,Walked to work,176429,5258,2.980236
31,Shasta,2,WALK,Walked to work,139792,2810,2.010129

Drop the column "county_name"

In [3]:
df_sorted = df_sorted.drop(columns=["county_name"])
df_sorted.to_excel("t2w_WALK.xlsx", index=False)
df_sorted.head()

    district_name  mode       mode_name  pop_total  pop_mode   percent
9               1  WALK  Walked to work    4395274    182448  4.151004
13              1  WALK  Walked to work     127885      5170  4.042695
5               1  WALK  Walked to work     116123      6284  5.411503
37              2  WALK  Walked to work     176429      5258  2.980236
31              2  WALK  Walked to work     139792      2810  2.010129

Clear the "percent" column

In [4]:
df_sorted["percent"] = None
df_sorted.to_excel("t2w_WALK.xlsx", index=False)
df_sorted.head()

    district_name  mode       mode_name  pop_total  pop_mode percent
9               1  WALK  Walked to work    4395274    182448    None
13              1  WALK  Walked to work     127885      5170    None
5               1  WALK  Walked to work     116123      6284    None
37              2  WALK  Walked to work     176429      5258    None
31              2  WALK  Walked to work     139792      2810    None

Merge the rows for each "district_name"

In [5]:
df_merged = df_sorted.groupby("district_name", as_index=False).agg({
    **{col: "first" for col in df_sorted.columns if col not in ["pop_total", "pop_mode", "district_name"]},
    "pop_total": "sum",
    "pop_mode": "sum"
})
df_merged.to_excel("t2w_WALK.xlsx", index=False)
df_merged.head()

   district_name  mode       mode_name percent  pop_total  pop_mode
0              1  WALK  Walked to work    None    4639282    193902
1              2  WALK  Walked to work    None     349586      9728
2              3  WALK  Walked to work    None    3718557    136671
3              4  WALK  Walked to work    None    6580289    237143
4              5  WALK  Walked to work    None    1094041     46654

Calculate the "percent" by formula: "pop_mode"/"pop_total"*100

In [6]:
df_merged["percent"] = (df_merged["pop_mode"] / df_merged["pop_total"]) * 100
df_merged.to_excel("t2w_WALK.xlsx", index=False)
df_merged.head()

   district_name  mode       mode_name   percent  pop_total  pop_mode
0              1  WALK  Walked to work  4.179569    4639282    193902
1              2  WALK  Walked to work  2.782720     349586      9728
2              3  WALK  Walked to work  3.675377    3718557    136671
3              4  WALK  Walked to work  3.603839    6580289    237143
4              5  WALK  Walked to work  4.264374    1094041     46654