Open "t2w_CARPOOL.xlsx" with pandas

In [1]:
import pandas as pd

df = pd.read_excel("t2w_CARPOOL.xlsx")
df.head()

,county_name,district_name,mode,mode_name,pop_total,pop_mode,percent
0,Alameda,4,CARPOOL,"Car, Truck, or Van: Carpooled",1378947,145808,10.573865
1,Butte,3,CARPOOL,"Car, Truck, or Van: Carpooled",175797,19585,11.140691
2,Contra Costa,4,CARPOOL,"Car, Truck, or Van: Carpooled",935733,115798,12.375111
3,El Dorado,3,CARPOOL,"Car, Truck, or Van: Carpooled",166652,18788,11.273792
4,Fresno,6,CARPOOL,"Car, Truck, or Van: Carpooled",702651,91675,13.047018

Sort the data by "district_name"

In [2]:
df_sorted = df.sort_values(by="district_name")
df_sorted.to_excel("t2w_CARPOOL.xlsx", index=False)
df_sorted.head()

,county_name,district_name,mode,mode_name,pop_total,pop_mode,percent
5,Humboldt,1,CARPOOL,"Car, Truck, or Van: Carpooled",116123,12934,11.138190
12,Mendocino,1,CARPOOL,"Car, Truck, or Van: Carpooled",74796,35429,47.367506
32,Siskiyou,2,CARPOOL,"Car, Truck, or Van: Carpooled",33365,4482,13.433238
31,Shasta,2,CARPOOL,"Car, Truck, or Van: Carpooled",139792,14540,10.401167
20,Sacramento,3,CARPOOL,"Car, Truck, or Van: Carpooled",1209828,615979,50.914593

Drop the column "county_name"

In [3]:
df_sorted = df_sorted.drop(columns=["county_name"])
df_sorted.to_excel("t2w_CARPOOL.xlsx", index=False)
df_sorted.head()

,district_name,mode,mode_name,pop_total,pop_mode,percent
5,1,CARPOOL,"Car, Truck, or Van: Carpooled",116123,12934,11.138190
12,1,CARPOOL,"Car, Truck, or Van: Carpooled",74796,35429,47.367506
32,2,CARPOOL,"Car, Truck, or Van: Carpooled",33365,4482,13.433238
31,2,CARPOOL,"Car, Truck, or Van: Carpooled",139792,14540,10.401167
20,3,CARPOOL,"Car, Truck, or Van: Carpooled",1209828,615979,50.914593

Clear the "percent" column

In [4]:
df_sorted["percent"] = None
df_sorted.to_excel("t2w_CARPOOL.xlsx", index=False)
df_sorted.head()

,district_name,mode,mode_name,pop_total,pop_mode,percent
5,1,CARPOOL,"Car, Truck, or Van: Carpooled",116123,12934,None
12,1,CARPOOL,"Car, Truck, or Van: Carpooled",74796,35429,None
32,2,CARPOOL,"Car, Truck, or Van: Carpooled",33365,4482,None
31,2,CARPOOL,"Car, Truck, or Van: Carpooled",139792,14540,None
20,3,CARPOOL,"Car, Truck, or Van: Carpooled",1209828,615979,None

Merge the rows for each "district_name"

In [5]:
df_merged = df_sorted.groupby("district_name", as_index=False).agg({
    **{col: "first" for col in df_sorted.columns if col not in ["pop_total", "pop_mode", "district_name"]},
    "pop_total": "sum",
    "pop_mode": "sum"
})
df_merged.to_excel("t2w_CARPOOL.xlsx", index=False)
df_merged.head()

,district_name,mode,mode_name,percent,pop_total,pop_mode
0,1,CARPOOL,"Car, Truck, or Van: Carpooled",None,190919,48363
1,2,CARPOOL,"Car, Truck, or Van: Carpooled",None,173157,19022
2,3,CARPOOL,"Car, Truck, or Van: Carpooled",None,2251682,885836
3,4,CARPOOL,"Car, Truck, or Van: Carpooled",None,6681497,839486
4,5,CARPOOL,"Car, Truck, or Van: Carpooled",None,1258819,313475

Calculate the "percent" by formula: "pop_mode"/"pop_total"*100

In [6]:
df_merged["percent"] = (df_merged["pop_mode"] / df_merged["pop_total"]) * 100
df_merged.to_excel("t2w_CARPOOL.xlsx", index=False)
df_merged.head()

,district_name,mode,mode_name,percent,pop_total,pop_mode
0,1,CARPOOL,"Car, Truck, or Van: Carpooled",25.331685,190919,48363
1,2,CARPOOL,"Car, Truck, or Van: Carpooled",10.985406,173157,19022
2,3,CARPOOL,"Car, Truck, or Van: Carpooled",39.341079,2251682,885836
3,4,CARPOOL,"Car, Truck, or Van: Carpooled",12.564340,6681497,839486
4,5,CARPOOL,"Car, Truck, or Van: Carpooled",24.902309,1258819,313475